@TodoApi_HostAddress = https://localhost:7005

GET {{TodoApi_HostAddress}}/todoitems

###

POST {{TodoApi_HostAddress}}/todoitems
Content-Type: application/json
{
  "name":"walk cat",
  "isComplete":false
}

###

GET {{TodoApi_HostAddress}}/todoitems/complete

###

DELETE {{TodoApi_HostAddress}}/todoitems/1

###

GET {{TodoApi_HostAddress}}/todoitems/1

###

PUT {{TodoApi_HostAddress}}/todoitems/1

###
